version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aiwoQwo520..
      MYSQL_DATABASE: saas_master
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - saas-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  app:
    image: ${DOCKER_USERNAME}/saas-app:latest
    container_name: saas-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=aiwoQwo520..
      - DB_DATABASE=saas_master
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=aiwoQwo520..
    networks:
      - saas-network

volumes:
  mysql_data:
    driver: local

networks:
  saas-network:
    driver: bridge 